obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.1

inflation_radius: 0.2
map_type: costmap
observation_sources: laser
laser: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}
